feat: implement version syncing from Podspec to Swift code and add User-Agent versioning

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Sync version from Podspec to Swift code
+./sync_pod_version.sh
+if [ $? -ne 0 ]; then
+    echo "Error syncing version."
+    exit 1
+fi
+
 # Run SwiftLint on the Sources directory
 ./run_swiftlint.sh
 
